route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: enter_bot_token
        api_url: 'https://api.telegram.org'
        chat_id: enter_chat_id
        parse_mode: ''
        message: "Alertmanager \n-- \n roflan: {{  .GroupLabels.alertname}}\n  "
