groups:
  - name: Critical alers
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
          summary: Instance {{ $labels.instance }} downestart=on-failure

      - alert: PrometheusConfigurationReloadFailure
        expr: prometheus_config_last_reload_successful != 1
        for: 5m
        labels:
          project: "{{$labels.project}}"
          severity: critical
        annotations:
          title: Prometheus configuration reload failure
          description: Prometheus configuration reload error

      - alert: PrometheusTooManyRestarts
        expr: changes(process_start_time_seconds{job=~"prometheus|alertmanager"}[15m]) > 2
        for: 5m
        labels:
          project: "{{$labels.project}}"
          severity: critical
        annotations:
          summary: Prometheus too many restarts
          description: Prometheus has restarted more than twice in the last 15 minutes. It might be crashlooping

      - alert: PrometheusNotificationsFailed
        expr: sum(increase(alertmanager_notifications_failed_total{integration="webhook"}[5m])) by (integration, job) > 40
        for: 5m
        labels:
          project: "{{$labels.project}}"
          severity: critical
        annotations:
          summary: Prometheus too many failed notifications
          description: Prometheus too many failed notifications

  - name: Systemd alerts
    rules:
      - alert: SystemdServiceFailed
        expr: node_systemd_unit_state{state="failed", name!="dnf-makecache.service"} == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          title: "{{ $labels.name }} failed"
          description: systemd service {{ $labels.name }} failed

      - alert: DiskBusy
        expr: rate(node_disk_io_time_seconds_total{device!~"(md|dm).*"}[5m]) * 100 > 90
        for: 1m
        labels:
          severity: warning
        annotations:
          title: '{{ $labels.device }} busy {{ $value | printf "%.0f"}}%'
          description: Disk {{ $labels.device }} busy {{ $value |printf "%.0f"}}%

      - alert: HostOutOfMemory
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes *100 < 10)
        for: 2m
        labels:
          severity: critical
        annotations:
          title: Host out of memory ({{ $value | printf "%.0f"}}%)
          description: Node memory is filling up ({{ $value | printf "%.0f"}}%< 10%)

      - alert: SystemLoad_5m
        expr: (avg by(job,instance) (node_load5) / count by(job,instance)(count by(cpu,job,instance) (node_cpu_seconds_total)) * 100) >= 100
        for: 1m
        labels:
          severity: "{{ if ge $value 105.0 }}critical{{ else }}warning{{ end}}"
        annotations:
          title: 'System Load 5m: {{ $value | printf "%.0f"}}%'
          description: System Load 5m too high ({{ $value | printf "%.0f"}}%)for 1 minutes

  - name: Hardware alerts
    rules:
      - alert: DiskSpace50%Free
        expr: node_exporter:node_filesystem_free:fs_used_percents >= 50
        labels:
          severity: moderate
        annotations:
          summary: "Instance {{ $labels.instance }} is half or lower on disk space"
          description: "{{ $labels.instance }} has only {{ $value }}% free."

      - alert: HighCpuLoad
        expr: (sum by (instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!="idle"}[2m]))) > 0.8) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostPhysicalComponentTooHot
        expr: ((node_hwmon_temp_celsius * ignoring(label) group_left(instance, job, node, sensor) node_hwmon_sensor_label{label!="tctl"} > 75)) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host physical component too hot (instance {{ $labels.instance }})
          description: "Physical hardware component too hot\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostNetworkBondDegraded
        expr: (node_bonding_active - node_bonding_slaves) != 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host Network Bond Degraded (instance {{ $labels.instance }})
          description: "Bond \"{{ $labels.device }}\" degraded on \"{{ $labels.instance }}\".\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostClockNotSynchronising
        expr: min_over_time(node_timex_sync_status[1m]) == 0 and node_timex_maxerror_seconds >= 16
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host clock not synchronising (instance {{ $labels.instance }})
          description: "Clock not synchronising. Ensure NTP is configured on this host.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - name: BlackBox alerts
    rules:
      - alert: BlackboxProbeFailed
        expr: probe_success{} != 1
        for: 2m
        labels:
          severity: critical
        annotations:
          title: "Blackbox probe failed. {{$labels.instance }}"
          description: 'Blackbox probe failed (instance {{ $labels.instance }})'
