- name: Copy Prometheus configuration file prometheus.yml.j2
  copy:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: prometheus_reload

- name: Copy Prometheus configuration file prometheus.j2
  copy:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: prometheus_restart

- name: Copy Alertmanager configuration file alertmanager.yml.j2
  copy:
    src: alertmanager.yml.j2
    dest: /etc/prometheus/alertmanager.yml
  notify: alertmanager_restart

- name: Copy Alertmanager configuration file prometheus-alertmanager.j2
  copy:
    src: prometheus-alertmanager.j2
    dest: /etc/default/prometheus-alertmanager
  notify: alertmanager_restart

- name: Copy Blackbox Exporter configuration file blackbox.yml.j2
  copy:
    src: blackbox.yml.j2
    dest: /etc/prometheus/blackbox.yml
  notify: blackbox_restart

- name: Copy Blackbox Exporter configuration file prometheus-blackbox.j2
  copy:
    src: prometheus-blackbox-exporter.j2
    dest: /etc/default/prometheus-blackbox-exporter
  notify: blackbox_restart

- name: Copy Alert Rules file
  copy:
    src: alert-rules.yml.j2
    dest: /etc/prometheus/alert-rules.yml
  notify: alertmanager_restart

- name: Copy Node Exporter configuration file prometheus-node-exporter.j2
  copy:
    src: prometheus-node-exporter.j2
    dest: /etc/default/prometheus-node-exporter
  notify: prometheus_restart
